# Generated by Django 3.2.14 on 2024-02-02 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='id',
            field=models.CharField(default='lZOCu3P9aNWXTnJDSGZNEw', editable=False, max_length=22, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='blogcomment',
            name='id',
            field=models.CharField(default='rCGLJH0vrDTHBdeBGealMS', editable=False, max_length=22, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='book',
            name='id',
            field=models.CharField(default='FTXDlUBv8mftOHVj5Gg10T', editable=False, max_length=22, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='comment_poll',
            name='id',
            field=models.CharField(default='crdj1mYELeHD85isvlLrkG', editable=False, max_length=22, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='poll',
            name='id',
            field=models.CharField(default='Q8yWlYfoqeXeBOj9ywCBgt', editable=False, max_length=22, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.CharField(default='Jh3grSvRsg', editable=False, max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='review',
            name='id',
            field=models.CharField(default='JzFrhcMmcAMxRWDGVMyb6n', editable=False, max_length=22, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default='dUGjEfp6iV', editable=False, max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vote',
            name='id',
            field=models.CharField(default='Zfjpm7M97vl2G3m5C1UXUI', editable=False, max_length=22, primary_key=True, serialize=False),
        ),
    ]
