# Generated by Django 3.2.14 on 2024-02-02 13:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20240202_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='id',
            field=models.CharField(default='kJud6dm204A3HcszvOxwfP', editable=False, max_length=22, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='blogcomment',
            name='id',
            field=models.CharField(default='gZg9j9BIW62vTPNnfF4NOr', editable=False, max_length=22, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='book',
            name='id',
            field=models.CharField(default='RUiiWMVV370Eefh4jiyDgI', editable=False, max_length=22, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='comment_poll',
            name='id',
            field=models.CharField(default='stGq3BlcE1Ykq8rOuDa3HN', editable=False, max_length=22, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='poll',
            name='id',
            field=models.CharField(default='hFttb2uTuHEtVbZmxDPX1W', editable=False, max_length=22, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.CharField(default='nrMSsNOtkm', editable=False, max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='review',
            name='id',
            field=models.CharField(default='Fb2TmD9xuIDVB4PMNoIkGo', editable=False, max_length=22, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vote',
            name='id',
            field=models.CharField(default='RCcYc8I6gSMSqxOQpbyKl9', editable=False, max_length=22, primary_key=True, serialize=False),
        ),
    ]
