# Generated by Django 3.2.14 on 2023-12-06 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20231129_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='content',
            field=models.TextField(default=''),
        ),
    ]
