# Generated by Django 3.2.14 on 2023-12-06 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_poll_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_polls', to='api.profile'),
        ),
    ]
