# Generated by Django 3.2.14 on 2023-12-14 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment_Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField(default='')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='api.profile')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_poll', to='api.poll')),
            ],
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
