# Generated by Django 3.2.14 on 2023-12-15 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_blog_tag'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
