# Generated by Django 3.2.14 on 2023-12-23 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blog', to='api.book'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blog', to='api.tag'),
        ),
    ]
