# Generated by Django 3.2.14 on 2023-12-23 05:23

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20231223_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='id',
            field=models.CharField(default=api.models.create_id, editable=False, max_length=22, primary_key=True, serialize=False),
        ),
    ]
