# Generated by Django 3.2.14 on 2024-01-09 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20231226_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_en',
            field=models.CharField(default='None Category', max_length=255, primary_key=True, serialize=False),
        ),
    ]
