# Generated by Django 3.2.14 on 2024-01-30 10:02

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_blog_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default.png', upload_to=api.models.user_directory_path),
        ),
    ]
