# Generated by Django 3.2.14 on 2024-02-02 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='id',
            field=models.CharField(default='pZFMl4x0r9fqc3jxxx0cu4', editable=False, max_length=22, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='blogcomment',
            name='id',
            field=models.CharField(default='Bfxr38G87SushnV0QBxkJE', editable=False, max_length=22, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default='WJhg1MCiUy', editable=False, max_length=10, primary_key=True, serialize=False),
        ),
    ]
