# Generated by Django 3.2.14 on 2024-02-02 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20240202_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='id',
            field=models.CharField(default='y5i6FZErNzQRFWKvmTFwoL', editable=False, max_length=22, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='blogcomment',
            name='id',
            field=models.CharField(default='a1vkUjaaSg7ZvMmSUnqBcO', editable=False, max_length=22, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default='Of8m3RB4DF', editable=False, max_length=10, primary_key=True, serialize=False),
        ),
    ]
