# Generated by Django 3.2.14 on 2024-02-02 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20240202_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='id',
            field=models.CharField(default='M8jBvkV5k6pGv3gFs4ksAj', editable=False, max_length=22, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='blogcomment',
            name='id',
            field=models.CharField(default='QDM0xGMz9JPXpmCCbqhfzn', editable=False, max_length=22, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='book',
            name='id',
            field=models.CharField(default='SpXkY2OuViTX7gI6xeBux7', editable=False, max_length=22, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='comment_poll',
            name='id',
            field=models.CharField(default='EjYxjOvIBgDloNnmOs1dWX', editable=False, max_length=22, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='poll',
            name='id',
            field=models.CharField(default='QcPDJXKyURz7SaAV7Ebuyy', editable=False, max_length=22, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.CharField(default='GUhaz2gsfW', editable=False, max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='review',
            name='id',
            field=models.CharField(default='4wgBarc4Xs7xF2d4VCJvg0', editable=False, max_length=22, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default='8s1SxCgasM', editable=False, max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vote',
            name='id',
            field=models.CharField(default='LgBlajmbLaQRffUkq51WUy', editable=False, max_length=22, primary_key=True, serialize=False),
        ),
    ]
